server:
  port: 8083

spring:
  application:
    name: security-orders
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/uaa/oauth/token

app:
  data:
    inject: true
  services:
    items: http://localhost:8082
