server:
  port: ${PORT:0}

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/uaa/oauth/token

app:
  data:
    inject: true
  services:
    items: //security-items

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
