spring:
  cloud:
    gateway:
      routes:
        - uri: http://localhost:8082
          predicates:
            - Path=/api/greetings

        - uri: http://localhost:8083
          predicates:
            - Path=/api/adder
          filters:
            - RewritePath=/api/adder(?<segment>.*),/api/calc/add$\{segment}

        - uri: http://localhost:8083
          predicates:
            - Path=/api/calc/**
