spring:
  cloud:
    gateway:
      routes:
        - uri: http://localhost:8082
          predicates:
            - Path=/api/greetings
        - uri: http://localhost:8081
          predicates:
            - Path=/api/adder
