spring:
  security:
    oauth2:
      client:
        provider:
          uaa:
            issuer-uri: http://localhost:8090/uaa/oauth/token
        registration:
          login-client:
            provider: uaa
            client-id: login-client
            client-secret: secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email,app.admin

  cloud:
    gateway:
      routes:
        - uri: http://localhost:8081
          predicates:
            - Path=/api/customers,/api/customers/**

        - uri: http://localhost:8082
          predicates:
            - Path=/api/items,/api/items/**

        - uri: http://localhost:8083
          predicates:
            - Path=/api/orders,/api/orders/**

      default-filters:
        - PreserveHostHeader
        - TokenRelay
