---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGateway
metadata:
  name: gateway
---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: gateway
spec:
  routes:
    - uri: http://greetings:8080
      predicates:
        - Path=/api/greetings
      filters:
        - StripPrefix=0

    - uri: http://adder:8080
      predicates:
        - Path=/api/adder
      filters:
        - StripPrefix=0
---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayMapping
metadata:
  name: gateway
spec:
  gatewayRef:
    name: gateway
  routeConfigRef:
    name: gateway
