server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: people
          uri: http://localhost:8082
          predicates:
            - Path=/api/people
            - Weight=people-legacy, 10

        - id: people-legacy
          uri: http://localhost:8080
          predicates:
            - Path=/api/people
            - Weight=people-legacy, 90
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenish-rate: 5
                  burst-capacity: 5
                  requestedTokens: 1

        - id: monolith
          uri: http://localhost:8080
          predicates:
            - Path=/**
