app:
  circuitbreaker:
    timeout: 2s

spring:
  cloud:
    gateway:
      routes:
        - id: greetings
          uri: http://localhost:8081
          predicates:
            - Path=/api/greetings
          filters:
            - name: CircuitBreaker
              args:
                name: greetings-circuitbreaker
                fallbackUri: forward:/api/fallback/greetings

        - id: greetings-slow
          uri: http://localhost:8081
          predicates:
            - Path=/api/greetings-slow
          filters:
            - name: CircuitBreaker
              args:
                name: greetings-circuitbreaker
                fallbackUri: forward:/api/fallback/greetings-slow

        - id: greeting-ratelimiting
          uri: http://localhost:8081
          predicates:
            - Path=/api/greetings-ratelimiting
          filters:
            - RewritePath=/api/greetings-ratelimiting(?<segment>.*),/api/greetings$\{segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenish-rate: 5
                  burst-capacity: 5
                  requestedTokens: 1

        - id: time-v1
          uri: http://localhost:8082
          predicates:
            - Path=/api/time
            - Weight=time, 90

        - id: time-v2
          uri: http://localhost:8083
          predicates:
            - Path=/api/time
            - Weight=time, 10
